# https://github.com/scala-steward-org/scala-steward/blob/master/docs/faq.md#how-can-scala-stewards-prs-be-merged-automatically
pull_request_rules:
  - name: label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [dependencies]
  - name: automatically merge PRs
    conditions:
      - or:
        - author=dependabot
        - author=scala-steward
    actions:
      merge:
        method: squash
        strict: true
