pull_request_rules:
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - check-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: squash
        strict: true
