name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  checks:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup scala
        uses: olafurpg/setup-scala@v13
      - name: Verify format
        run: ./bin/scalafmt --test
  test:
    name: Test
    strategy:
      matrix:
        scala:
          - 2.13.6
        java:
          - adopt@1.11
          - adopt@1.15
        os:
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Run tests (${{ matrix.scala }}, ${{ matrix.java }})
        run: sbt ++${{ matrix.scala }} clean test
