name: Continuous Integration

# TODO deploy/release gh-pages
# TODO jdk11

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup scala
        uses: olafurpg/setup-scala@v12

      - name: Run tests
        run: sbt clean test
