name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    strategy:
      matrix:
        scala:
          - 2.13.8
        java:
          - adopt@1.11
          - openjdk@1.17
        os:
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    # TODO obsolete https://github.com/olafurpg/setup-scala/issues/49
      - name: Setup scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Run tests (${{ matrix.scala }}, ${{ matrix.java }})
        run: sbt ++${{ matrix.scala }} build
